# Generated by Django 4.2 on 2024-06-06 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(max_length=400, verbose_name='Текст запроса пользователя')),
                ('completed', models.BooleanField(default=False, verbose_name='Готов')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аналитический отчет',
                'verbose_name_plural': 'Аналитические отчеты',
            },
        ),
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название файла')),
                ('file', models.FileField(upload_to='files/')),
            ],
            options={
                'verbose_name': 'Файл пользователя',
                'verbose_name_plural': 'Пользовательские файлы',
            },
        ),
        migrations.CreateModel(
            name='WebVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Содержание видео')),
                ('accounts', models.ManyToManyField(related_name='videos', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Содержание страницы')),
                ('update_date', models.DateTimeField(verbose_name='Дата обновления')),
                ('accounts', models.ManyToManyField(related_name='pages', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Интернет страница',
                'verbose_name_plural': 'Интернет страницы',
            },
        ),
    ]
