# Generated by Django 4.2 on 2024-06-07 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('web_page', 'Страница в интернете'), ('video', 'Видео'), ('file', 'Пользовательский файл')], max_length=16, verbose_name='Тип источника данных')),
                ('url', models.CharField(blank=True, max_length=1024, verbose_name='URL')),
                ('data_type', models.CharField(choices=[('series', 'Временной ряд'), ('reference', 'Справочник')], max_length=16, verbose_name='Тип данных')),
                ('data', models.JSONField(verbose_name='Данные')),
                ('date', models.DateTimeField(verbose_name='Дата создания версии')),
                ('version', models.PositiveIntegerField(verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
            },
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Содержание страницы')),
                ('update_date', models.DateTimeField(null=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Интернет страница',
                'verbose_name_plural': 'Интернет страницы',
            },
        ),
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название файла')),
                ('file', models.FileField(upload_to='files/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Файл пользователя',
                'verbose_name_plural': 'Пользовательские файлы',
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400, verbose_name='Текст запроса пользователя')),
                ('updates_subscribe', models.BooleanField(default=False, verbose_name='Подписка на обновления')),
                ('data', models.ManyToManyField(related_name='search_queries', to='accounts.data', verbose_name='Данные')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='accounts.userfiles', verbose_name='Пользовательский файл'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', models.ManyToManyField(related_name='accounts', to='accounts.data', verbose_name='Данные')),
                ('search_query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.searchquery', verbose_name='Поисковый запрос')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аналитический отчет',
                'verbose_name_plural': 'Аналитические отчеты',
            },
        ),
    ]
