# Generated by Django 4.2 on 2024-06-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание страницы'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='update_date',
            field=models.DateTimeField(null=True, verbose_name='Дата обновления'),
        ),
    ]
