# Generated by Django 4.2 on 2024-06-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='meta_data',
            field=models.JSONField(default={}, verbose_name='Мета данные'),
            preserve_default=False,
        ),
    ]
