# Generated by Django 4.2 on 2024-06-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.CharField(choices=[('series', 'Временной ряд'), ('reference', 'Справочник')], verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='data',
            name='type',
            field=models.CharField(choices=[('web_page', 'Страница в интернете'), ('video', 'Видео'), ('file', 'Пользовательский файл')], verbose_name='Тип источника данных'),
        ),
    ]
