# Generated by Django 4.2 on 2024-06-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_data_data_type_alter_data_type'),
        ('accounts', '0002_data_meta_data'),
    ]

    operations = [
    ]
