# Generated by Django 4.2 on 2024-06-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_webpage_content_alter_webpage_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='user_add',
            field=models.BooleanField(default=False, verbose_name='Добавлено пользователем'),
        ),
    ]
