# Generated by Django 4.2 on 2024-06-10 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_merge_20240609_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', models.ManyToManyField(related_name='reports', to='accounts.data', verbose_name='Данные')),
                ('search_query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='accounts.searchquery', verbose_name='Поисковый запрос')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аналитический отчет',
                'verbose_name_plural': 'Аналитические отчеты',
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
