# Generated by Django 4.2 on 2024-06-10 11:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_report_delete_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFiles',
            new_name='Files',
        ),
    ]
