# Generated by Django 4.2 on 2024-06-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_userfiles_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='index_id',
            field=models.CharField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='searchquery',
            constraint=models.UniqueConstraint(fields=('user', 'text'), name='accounts_searchquery_uniq'),
        ),
    ]
