# Generated by Django 4.2 on 2024-06-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_data_index_id_searchquery_accounts_searchquery_uniq'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='title',
            field=models.CharField(default='', verbose_name='Title'),
            preserve_default=False,
        ),
    ]
