# Generated by Django 4.2 on 2024-06-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_webpage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='url',
        ),
        migrations.AddField(
            model_name='data',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='accounts.webpage', verbose_name='Интернет страницы'),
        ),
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='accounts.files', verbose_name='Пользовательский файл'),
        ),
    ]
