# Generated by Django 4.2 on 2024-06-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_data_url_data_page_alter_data_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='data',
        ),
        migrations.CreateModel(
            name='ReportBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_blocks', to='accounts.data', verbose_name='Данные')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='accounts.report', verbose_name='Отчет')),
            ],
        ),
    ]
