# Generated by Django 4.2 on 2024-06-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_report_data_reportblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='data',
            field=models.ManyToManyField(related_name='reports', through='accounts.ReportBlock', to='accounts.data', verbose_name='Данные'),
        ),
    ]
