# Generated by Django 4.2 on 2024-06-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_reportblock_representation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тематика отчета',
                'verbose_name_plural': 'Тематики отчетов',
            },
        ),
        migrations.AddField(
            model_name='reportblock',
            name='readiness',
            field=models.CharField(choices=[('ready', 'Готов'), ('not_ready', 'Не готов'), ('error', 'Ошибка')], default='ready', verbose_name='Готовность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportblock',
            name='type',
            field=models.CharField(default='type', verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='accounts.theme', verbose_name='Тематика отчета')),
            ],
            options={
                'verbose_name': 'Шаблон отчета',
                'verbose_name_plural': 'Шаблоны отчетов',
            },
        ),
        migrations.CreateModel(
            name='MetaBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_template', models.CharField(verbose_name='Шаблон запроса')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_blocks', to='accounts.template', verbose_name='Шаблон отчета')),
            ],
            options={
                'verbose_name': 'Мета-блок отчета',
                'verbose_name_plural': 'Мета-блоки отчетов',
            },
        ),
    ]
