# Generated by Django 4.2 on 2024-06-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_theme_reportblock_readiness_reportblock_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metablock',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция'),
            preserve_default=False,
        ),
    ]
