# Generated by Django 4.2 on 2024-06-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_metablock_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportblock',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_blocks', to='accounts.data', verbose_name='Данные'),
        ),
    ]
