# Generated by Django 4.2 on 2024-06-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_reportblock_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportblock',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_blocks', to='accounts.data', verbose_name='Данные'),
        ),
    ]
