# Generated by Django 4.2 on 2024-06-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_reportblock_comment_reportblock_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.CharField(choices=[('plotly', 'plotly'), ('text', 'Текст')], verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='metablock',
            name='type',
            field=models.CharField(choices=[('plotly', 'Plotly'), ('text', 'Текст'), ('video', 'Видео')], verbose_name='Тип'),
        ),
    ]
