# Generated by Django 4.2 on 2024-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_reportblock_comment_reportblock_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-pk',), 'verbose_name': 'Аналитический отчет', 'verbose_name_plural': 'Аналитические отчеты'},
        ),
        migrations.AddField(
            model_name='report',
            name='search_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='search_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.CharField(choices=[('plotly', 'plotly'), ('text', 'Текст')], verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='metablock',
            name='type',
            field=models.CharField(choices=[('plotly', 'Plotly'), ('text', 'Текст'), ('video', 'Видео')], verbose_name='Тип'),
        ),
    ]
